var nodes={
			text:'人力资源管理子系统',
			expanded:true,
			leaf:false,
			children:[
			          {
			          	  id:'zzjg',
			          	  text:'组织机构管理',
			          	  expanded:false,
			        	  leaf:false,
			        	  children:[
			        	  		{
			        	  			id:'generalAffairsDepartment',
			        	  			text:'总务部',
			        	  			leaf:true
			        	  		},{
			        	  			id:'HR',
			        	  			text:'人资部',
			        	  			leaf:true
			        	  		},{
			        	  			id:'financialDepartment',
			        	  			text:'财务部',
			        	  			leaf:true
			        	  		},{
			        	  			id:'businessDepartment',
			        	  			text:'业务部',
			        	  			leaf:true
			        	  		},{
			        	  			id:'networkDepartment',
			        	  			text:'网络部',
			        	  			leaf:true
			        	  		}
			        	  ]
			          },
			          {
			        	  id:'zcgl',
			        	  text:'职称岗位管理',
			        	  expanded:false,
			        	  leaf:false,
			        	  children :[
			        	             {
			        	             	 id:'nameManager',
			        	            	 text:'职称管理',
			        	            	 leaf:true
			        	             },
			        	             {
			        	             	 id:'positionManager',
			        	            	 text:'岗位管理',
			        	            	 leaf:true
			        	             }
			        	             ]
			          },
			          {
			        	  id:'yggl',
			        	  text:'员工管理',
			        	  expanded:false,
			        	  leaf:false,
			        	  children :[
			        	             {
			        	             	 id:'staffEntryManager',
			        	            	 text:'员工入职管理',
			        	            	 leaf:true
			        	             },
			        	             {
			        	             	 id:'staffInfoManager',
			        	            	 text:'员工信息维护',
			        	            	 leaf:true
			        	             },
			        	             {
			        	             	 id:'staffJobInfoManager',
			        	            	 text:'员工任职信息管理',
			        	            	 leaf:true
			        	             }
			        	             ]
			          },
			          {
			        	  id:'cxtj',
			        	  text:'查询统计',
			        	  expanded:false,
			        	  leaf:false,
			        	  children :[
			        	             {
			        	             	 id:'allFind',
			        	            	 text:'综合查询',
			        	            	 leaf:true
			        	             },
			        	             {
			        	             	 id:'summarizingStatistics',
			        	            	 text:'汇总统计',
			        	            	 leaf:true
			        	             }
			        	             ]
			          }
			         ]
			
	};